hConEnc = comm.ConvolutionalEncoder(...                                    %One (2,1,7)Convolutional code
    'TrellisStructure',poly2trellis(7,[171 133]), ...            
    'TerminationMethod','Truncated');
hAPPDec = comm.APPDecoder(...                                              % App decoder
    'TrellisStructure',poly2trellis(7,[171 133]), ...
    'Algorithm','True APP','CodedBitLLROutputPort',false);

hMod = comm.PSKModulator(4,'BitInput',true,'PhaseOffset',0);               %psk modulator
hDemod = comm.PSKDemodulator(4,'BitOutput',true,'PhaseOffset',0, ...
    'DecisionMethod','Approximate log-likelihood ratio', ...
    'Variance',noiseVar);    

hChan = comm.AWGNChannel('NoiseMethod','Variance', ...
    'Variance',noiseVar);
pathDelays = [0 200 800 1200 2300 3700]*1e-5;    % sec
avgPathGains = [0 -3 -4.9 -8 -7.8 -23.9];        % dB
fD = 0;                                          % Hz
% rchan = comm.RayleighChannel('SampleRate',fs, ...
%     'PathDelays',pathDelays, ...
%     'AveragePathGains',avgPathGains, ...
%     'MaximumDopplerShift',fD, ...
%     'Visualization','Impulse and frequency responses');
rchan = comm.RayleighChannel('SampleRate',fs, ...                          % Channel
    'PathDelays',pathDelays, ...
    'AveragePathGains',avgPathGains, ...
    'MaximumDopplerShift',fD);

hError = comm.ErrorRate;                                                   % ErrorRate computer
